# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proto1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets as qtw
import sys
from import_data import Text
from bio_proto_gui import Ui_MainWindow
from Features import Feature

class MainWindow(qtw.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.show()
        self.feat=Feature()
        self.ui.actionText_File.triggered.connect(self.get_data)
        self.ui.actionFrequency.triggered.connect(self.freq_view)
        self.ui.actionTranscription.triggered.connect(self.transcript_view)

    def get_data(self):
        func=Text()
        self.data = str(func.data())
        self.ui.label.setText(self.data)
    def freq_view(self):
        freqs=self.feat.nucleotide_frequency(self.data)
        self.ui.label.setText(str(freqs))
    def transcript_view(self):
        trans = self.feat.transcription(self.data)
        self.ui.label.setText(str(trans))
if __name__ == '__main__':
    app = qtw.QApplication(sys.argv)
    app.setStyle("Fusion")
    mw = MainWindow()
    sys.exit(app.exec_())
